source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/elegion/ios-podspecs.git'

target 'example', :exclusive => true do
    pod 'ELNBehaviors', :path => '../'
end

target 'exampleTests', :exclusive => true do
    pod 'ELNBehaviors', :path => '../'
end
